FROM postgres:16-alpine

ENV POSTGRES_USERNAME=low-code
ENV POSTGRES_PASSWORD=lowcodetableapi
ENV POSTGRES_DB=table_db

ENV PGSQL_AUTHENTICATOR=authenticator
ENV PGSQL_AUTHENTICATOR_PASSWORD=chameleonpassword

# Copy the initialization scripts into the Docker image
COPY ./01-init.sh /docker-entrypoint-initdb.d/01-init-table-db.sh
COPY ./02-auto-schema-cache-reload.sql /docker-entrypoint-initdb.d/02-auto-schema-cache-reload.sql
COPY ./03-stored-procedures.sql /docker-entrypoint-initdb.d/03-stored-procedures.sql

RUN chmod +x /docker-entrypoint-initdb.d/01-init-table-db.sh
