streams:
  - nats-config:
      name: WORKFLOW
      subjects:
        - WORKFLOW.System.Task.Create
        - WORKFLOW.System.Task.Update
        - WORKFLOW.System.Process.Pause
        - WORKFLOW.System.Process.Error
        - WORKFLOW.*.State.Job.Abort.*
        - WORKFLOW.*.State.Job.Complete.*
        - WORKFLOW.*.State.Activity.Abort
        - WORKFLOW.*.State.Activity.Complete
        - WORKFLOW.*.State.Activity.Execute
        - WORKFLOW.*.Command.>
        - WORKFLOW.*.Timers.ElementExecute
        - WORKFLOW.*.State.Execution.>
        - WORKFLOW.*.State.Job.Execute.AwaitMessage
        - WORKFLOW.*.State.Job.Execute.Launch
        - WORKFLOW.*.State.Job.Execute.ManualTask
        - WORKFLOW.*.State.Job.Execute.SendMessage.>
        - WORKFLOW.*.State.Job.Execute.ServiceTask.>
        - WORKFLOW.*.State.Job.Execute.Gateway
        - WORKFLOW.*.State.Job.Execute.Timer
        - WORKFLOW.*.State.Job.Execute.UserTask
        - WORKFLOW.*.State.Log.*
        - WORKFLOW.*.Message
        - WORKFLOW.*.State.Process.Complete
        - WORKFLOW.*.State.Process.Execute
        - WORKFLOW.*.State.Process.Terminated
        - WORKFLOW.*.Timers.WorkflowExecute
        - WORKFLOW.*.State.Traversal.Complete
        - WORKFLOW.*.State.Traversal.Execute
        - WORKFLOW.*.State.Job.Activate.Gateway
        - WORKFLOW.*.State.Job.ReEnter.Gateway
        - WORKFLOW.Message.Telemetry
        - WORKFLOW.Message.Kick
        - $JS.EVENT.ADVISORY.CONSUMER.MAX_DELIVERIES.WORKFLOW.>
      retention: 1
      storage: 1
    nats-consumers:
      - nats-config:
          durable_name: JobAbortConsumer
          description: Abort job message queue
          deliver_policy: 0
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.Abort.*
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: GeneralAbortConsumer
          description: Abort workflow instance and activity message queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.*.Abort
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: LaunchConsumer
          description: Sub workflow launch message queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.Execute.Launch
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: Message
          description: Intra-workflow message queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.Message
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: WorkflowConsumer
          description: Workflow processing queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Execution.>
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: ProcessCompleteConsumer
          description: Process complete processing queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Process.Complete
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: JobCompleteConsumer
          description: Job complete processing queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.Complete.*
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: ActivityConsumer
          description: Activity complete processing queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Activity.>
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: Traversal
          description: Traversal processing queue
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Traversal.Execute
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: Tracking
          description: Tracking queue for sequential processing
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.>
          max_ack_pending: 1
          max_batch: 1
      - nats-config:
          durable_name: GatewayExecuteConsumer
          description: Tracking queue for gateway execution
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.Execute.Gateway
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: GatewayActivateConsumer
          description: Tracking queue for gateway activation
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.Activate.Gateway
          max_ack_pending: 1
          max_batch: 1
      - nats-config:
          durable_name: GatewayReEnterConsumer
          description: Tracking queue for gateway activation
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.ReEnter.Gateway
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: AwaitMessageConsumer
          description: Tracking queue for gateway activation
          ack_policy: 2
          ack_wait: 30s
          filter_subject: WORKFLOW.*.State.Job.Execute.AwaitMessage
          max_ack_pending: 65535
          max_batch: 1
      - nats-config:
          durable_name: MessageKickConsumer
          description: Message processing consumer timer
          ack_policy: 2
          ack_wait: 2m0s
          filter_subject: WORKFLOW.Message.Kick
          max_ack_pending: 1
          max_batch: 1
      - nats-config:
          durable_name: TelemetryTimerConsumer
          description: Server telemetry timer
          ack_policy: 2
          ack_wait: 1s
          filter_subject: WORKFLOW.Message.Telemetry
          max_ack_pending: 1
          max_batch: 1
      - nats-config:
          durable_name: UndeliveredMsgConsumer
          description: Undeliverable workflow message queue.  Messages should be looked up in the WORKFLOW-MIRROR stream to avoid disappointment.
          ack_policy: 2
          ack_wait: 1s
          filter_subject: $JS.EVENT.ADVISORY.CONSUMER.MAX_DELIVERIES.WORKFLOW.>
  - nats-config:
      name: WORKFLOW-MIRROR
      retention: 0
      max_consumers: 0
      max_msgs: 0
      max_bytes: 0
      discard: 0
      max_age: 36h0m0s
      max_msgs_per_subject: 0
      storage: 1
      num_replicas: 0
      sources:
        - name: WORKFLOW
          filter_subject: WORKFLOW.*.State.>
      compression: 0
      allow_direct: false
      mirror_direct: false
    nats-consumers: []
buckets:
  - nats-config:
      bucket: WORKFLOW_MESSAGES
      description: ""
  - nats-config:
      bucket: WORKFLOW_CLIENTS
      description: ""
      ttl: 1.5s
  - nats-config:
      bucket: WORKFLOW_NAME
      description: ""
  - nats-config:
      bucket: WORKFLOW_DEF
      description: ""
  - nats-config:
      bucket: WORKFLOW_CLIENTTASK
      description: ""
  - nats-config:
      bucket: WORKFLOW_GATEWAY
      description: ""
  - nats-config:
      bucket: WORKFLOW_VARSTATE
      description: ""
  - nats-config:
      bucket: WORKFLOW_GENLCK
      description: ""
      ttl: 30s
  - nats-config:
      bucket: WORKFLOW_TSKSPEC
      description: ""
  - nats-config:
      bucket: WORKFLOW_EXECUTION
      description: ""
  - nats-config:
      bucket: WORKFLOW_TRACKING
      description: ""
#  - nats-config:
#      bucket: WORKFLOW_MSGNAME
#      description: ""
  - nats-config:
      bucket: WORKFLOW_OWNERID
      description: ""
  - nats-config:
      bucket: WORKFLOW_OWNERNAME
      description: ""
  - nats-config:
      bucket: WORKFLOW_HISTORY
      description: ""
  - nats-config:
      bucket: WORKFLOW_TSPECVER
      description: ""
  - nats-config:
      bucket: WORKFLOW_PROCESS_MAPPING
      description: ""
#  - nats-config:
#      bucket: WORKFLOW_INSTANCE
#      description: ""
  - nats-config:
      bucket: WORKFLOW_JOB
      description: ""
  - nats-config:
      bucket: WORKFLOW_VERSION
      description: ""
  - nats-config:
      bucket: WORKFLOW_USERTASK
      description: ""
  - nats-config:
      bucket: WORKFLOW_PROCESS
      description: ""
  - nats-config:
      bucket: WORKFLOW_MSGTYPES
      description: ""