steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/low-code-api:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/low-code-api:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'low-code-api'
   - '--image'
   - 'gcr.io/$PROJECT_ID/low-code-api:$COMMIT_SHA'
   - '--region'
   - 'asia-east2'
images:
 - 'gcr.io/$PROJECT_ID/low-code-api:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY