version: '3'
services:
  api:
    container_name: nestjs
    image: low-code-api-dev
    build:
      context: '.'
      dockerfile: Dockerfile
      target: development
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

    command: npx nest start --watch

  postgres:
    image: mysql:8.0
    restart: always
    
    env_file:
      - .env
