FROM node:20 AS builder

WORKDIR /app

COPY yarn.lock package.json tsconfig.json tsconfig.build.json ./
COPY prisma ./prisma/

RUN yarn install --frozen-lockfile
RUN yarn prisma generate

RUN yarn build

COPY . .

FROM node:20-slim AS production
RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

CMD [ "node", "dist/src/main.js" ]
EXPOSE 3000
