FROM node:20 AS builder

WORKDIR /app

COPY yarn.lock package.json ./
COPY prisma ./prisma/

RUN yarn install --frozen-lockfile
RUN yarn add @nestjs/cli -g

COPY . .

RUN yarn run prisma generate

CMD [ "yarn", "run", "start:dev" ]
EXPOSE 3000
