FROM node:18-alpine AS builder

WORKDIR /app

COPY yarn.lock package.json ./
COPY prisma ./prisma/

RUN yarn install --frozen-lockfile

COPY . .

FROM node:18-alpine AS production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package.json yarn.lock ./
COPY ./start-prod.sh ./start-prod.sh

RUN yarn add @nestjs/cli -g
RUN yarn install --frozen-lockfile --production

RUN chmod +x ./start-prod.sh
ENTRYPOINT [ "./start-prod.sh" ]

EXPOSE 3000
CMD [ "yarn", "run", "start:prod" ]