FROM node:18-alpine AS development

WORKDIR /app

COPY yarn.lock package.json ./
COPY prisma ./prisma/

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn add @nestjs/cli -g

#RUN chmod +x ./start-dev.sh
#ENTRYPOINT [ "./start-dev.sh" ]
RUN yarn run prisma generate

EXPOSE 3000
CMD [ "yarn", "run", "start:dev" ]