FROM postgres:16-alpine

ENV POSTGRES_USERNAME=low-code
ENV POSTGRES_PASSWORD=lowcodeuserapi
ENV POSTGRES_DB=user-db

# Copy the initialization scripts into the Docker image
COPY ./init.sh /docker-entrypoint-initdb.d/init-user-db.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-user-db.sh
