FROM golang:1.22-alpine3.19 as builder
WORKDIR /myapp
# Copy the go mod and sum files
COPY go.* ./
# Create app directory
RUN mkdir /myapp/app
RUN mkdir /myapp/shar
COPY ./app/go.* ./app
COPY ./shar/go.* ./shar
# Download the go dependencies
RUN go mod download
COPY . ./
# Copy the source code
# Buildthe webserver
RUN go build -v -o server ./app/cmd/main.go

FROM debian:buster-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /myapp/server /app/server

WORKDIR /app

CMD ["./server"]


