apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.telemetryName }}
  labels:
    {{- include "shar.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "shar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.telemetryName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.telemetryRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          env:
            - name: NATS_URL
              value: {{ include "shar.natsURL" . }}
            - name: JAEGER_URL
              value: {{ include "shar.jaegerURL" . }}
            - name: SHAR_LOG_LEVEL
              value: {{ .Values.service.loglevel }}
          #livenessProbe:
          #  grpc:
          #    port: grpc
          #readinessProbe:
          #  grpc:
          #    port: grpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
