global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /api/metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['user-api:3000']
  #- job_name: 'node-exporter'
  #  static_configs:
  #    - targets: ['node_exporter:9100']

  #- job_name: 'cadvisor'
  #  static_configs:
  #    - targets: ['cadvisor:8098']
