FROM envoyproxy/envoy:v1.21-latest

COPY ./envoy-http-proxy.yml /tmpl/envoy.yaml.tmpl
COPY envoy-docker-entrypoint.sh docker-entrypoint.sh

RUN chmod 500 /docker-entrypoint.sh

RUN apt-get update && \
    apt-get install gettext -y

ENTRYPOINT ["/docker-entrypoint.sh"]