services:
  nats:
    ports:
      - '4222:4222'
    image: nats:2.8.4
    command:
      - '--js'
      - '--server_name'
      - compose_nats

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - '16686:16686'
      - '14268:14268'