# Lightweight docker compose using the all in 
# one docker file in this directory.
#
# Example usage:
#
# > docker compose build
# (builds the compose services images from scratch)
#
# > docker compose up
# (runs the services with the available latest image)
services:
  shar-server:
    image: registry.gitlab.com/shar-workflow/shar/server:latest
    build:
      context: ../..
      dockerfile: .
    restart: on-failure
    environment:
      - NATS_URL=nats://nats:4222
  shar-telemetry:
    image: registry.gitlab.com/shar-workflow/shar/telemetry:latest
    build:
      context: .
      dockerfile: .
    restart: on-failure
    environment:
      - NATS_URL=nats://nats:4222
  nats:
    ports:
      - '4222:4222'
    image: nats:2.8.4
    command:
      - '--js'
      - '--server_name'
      - compose_nats

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - '16686:16686'
      - '14268:14268'