services:
  nats:
    ports:
      - '4222:4222'
    image: nats:2.8.4
    command:
      - '--js'
      - '--server_name'
      - compose_nats
  shar:
    image: registry.gitlab.com/shar-workflow/shar/server:1.0.532
    environment:
      - SHAR_PORT=50000
      - NATS_URL=nats://nats:4222
#  jaeger:
#    image: jaegertracing/all-in-one
#    ports:
#      - '16686:16686'
#      - '14268:14268'