version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  #yalc-server:
  #  build:
  #    context: .
  #    dockerfile: ./app/Dockerfile.dev
  #  networks:
  #    - mynetwork
  #  ports:
  #    - '3000:3000'
  #  volumes:
  #    - ./app/.env.local:/app/.env.local
  #    - ./app/service-tasks/:/app/service-tasks
  #  depends_on:
  #    nats:
  #      condition: service_started
  #    server:
  #      condition: service_started

  nats:
    image: nats:2.10-alpine3.19
    networks:
      - mynetwork
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    command:
      - '--js'
      - '--server_name'
      - 'nats'
      - '-m'
      - '8222'

  server:
    image: registry.gitlab.com/shar-workflow/shar/dev/server:latest
    networks:
      - mynetwork
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      nats:
        condition: service_started
