FROM golang:1.22-bullseye as builder
WORKDIR /app
# Copy the go mod and sum files
COPY go.* ./
# Create app directory
RUN mkdir /app/app
RUN mkdir /app/shar
COPY ./app/go.* ./app
COPY ./shar/go.* ./shar
# Download the go dependencies
RUN go mod download
COPY . ./
# Copy the source code
# Buildthe webserver
RUN go build -v -o server ./app/cmd/main.go

FROM debian:buster-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/server /app/server
# Copy the service task definitions
COPY --from=builder /app/app/service-tasks/*.yaml /app/service-tasks/

WORKDIR /app

ENV ENVIRONMENT=development

EXPOSE 3000

CMD ["./server"]


