FROM postgrest/postgrest

# Ignores the privileges of the JWT role claim (or from db-anon-role if the JWT is not sent)
# Shows all the exposed information, regardless of the permissions that the role making the request has
ENV PGRST_OPENAPI_MODE=ignore-privileges

# Copy the configuration file into the Docker image
COPY ./postgrest.conf /etc/postgrest.conf

# Set the default command to run when starting a container
CMD ["postgrest", "/etc/postgrest.conf"]